### ISSUE TITLE
兼容性问题请教

### ISSUE THREAD

**Issue by happysky-12** [Lyaiya/ModList#1]
打扰了，MC新手。请问核心系里的”科技“、”魔法“和”冒险“类mod彼此兼容么？我是否可以在三个类里各选择一个mod安装，还是总共只能选择一个mod？

**Comment by Lyaiya** [comment]
兼容一词在 MC 模组里的意思是有联动内容，你指的应该是有没有冲突，这种模组一般是没有冲突，可以放心一起安装。

**Comment by Lyaiya** [comment]
核心在这里是指大型、自成体系的模组。一般是不影响其他模组的，所以你装几个科技模组、装几个魔法模组、装几个冒险模组，甚至一起装都没问题。

**Comment by happysky-12** [comment]
谢谢

**Comment by Lyaiya** [comment]
没其他问题我就关了
